// CS 374 A, Homework 4, Problem 2
#import "../../setup.typ": *

#let llm-note = [
  I used Claude (Anthropic) to draft these grammars and explain their structure
  to me. I checked every grammar by hand against the examples in the handout and
  against several strings inside and outside each language, and typeset the
  submission myself.
]

#show: homework.with(
  title: "CS 374: Section A - Homework 4, Problem 2",
  date: "September 22, 2026",
)

Throughout, $Sigma = {0, 1}$, and $\#(a, x)$ denotes the number of occurrences of
the symbol $a$ in the string $x$.

= Part (a)

All strings in which every prefix has at least as many 1s as 0s, that is,

$
{w in Sigma^* | \#(1, x) >= \#(0, x) "for every prefix" x "of" w}.
$

#boxed[
$
S &-> epsilon | 1 S | 1 B 0 S & #h(1.5em) "every prefix has at least as many 1s as 0s" \
B &-> epsilon | 1 B 0 B & #h(1.5em) "balanced, every prefix has at least as many 1s as 0s"
$
]

For a string $u$ write $d(u) = \#(1, u) - \#(0, u)$. The two non-terminals
generate the following languages.

- $B$ generates every string $u$ with $d(u) = 0$ such that $d(x) >= 0$ for every
  prefix $x$ of $u$. These are the strings with equally many 0s and 1s in which
  no prefix has more 0s than 1s.

- $S$ generates every string $w$ such that $d(x) >= 0$ for every prefix $x$ of
  $w$, which is exactly the language asked for.

*Why this is correct.* Reading a 1 raises $d$ by one and reading a 0 lowers it by
one, so $d$ of a prefix is the running count that the language constrains. Each
description is checked in both directions.

_Every string $B$ generates is balanced with non-negative prefix counts._ This is
clear for $epsilon$. If $u, v in B$, then the prefixes of $1 u 0 v$ are the
strings $1 u'$, with $d = 1 + d(u') >= 1$, and the strings $1 u 0 v'$, with
$d = 1 + 0 - 1 + d(v') >= 0$. The whole string has $d(1 u 0 v) = 0$.

_Every such string is generated by $B$._ Let $u$ be non-empty with $d(u) = 0$ and
$d(x) >= 0$ for every prefix $x$. Its first symbol is 1, since the prefix $0$
would have $d = -1$. Let $i$ be the smallest index with $d(u[1 .. i]) = 0$; this
index exists because $d(u) = 0$, and $i >= 2$. Then $u[i] = 0$, because
$d(u[1 .. i - 1]) >= 1$ by the choice of $i$. So

$
u = 1 y 0 z, #h(1.5em) "where" y = u[2 .. i - 1] "and" z = u[i + 1 .. ].
$

Here $d(y) = 0$, and every prefix $y'$ of $y$ has $d(y') = d(1 y') - 1 >= 0$,
again by the choice of $i$, so $y in B$. And $z$ is the rest of $u$ after a
prefix with $d = 0$, so $d(z) = 0$ and every prefix of $z$ has $d >= 0$, so
$z in B$. This is the rule $B -> 1 B 0 B$, and induction on length finishes the
argument.

_Every string $S$ generates has non-negative prefix counts._ This is clear for
$epsilon$. If $w in S$, then every prefix of $1 w$ has $d = 1 + d(w') >= 1$. If
$u in B$ and $w in S$, then the prefixes of $1 u 0 w$ have $d >= 1$, then
$d = 0$, then $d = d(w') >= 0$.

_Every such string is generated by $S$._ Let $w$ be non-empty with $d(x) >= 0$
for every prefix $x$, and apply the hint.

- If no non-empty prefix $x$ of $w$ has $d(x) = 0$, then every non-empty prefix
  has $d >= 1$. In particular $w = 1 v$, and every prefix $v'$ of $v$ has
  $d(v') = d(1 v') - 1 >= 0$, so $v in S$ and $w$ comes from $S -> 1 S$.

- Otherwise let $x$ be the shortest non-empty prefix with $d(x) = 0$. Exactly as
  in the argument for $B$, we have $x = 1 y 0$ with $y in B$, and the remaining
  suffix $w'$ has $d(w'') = d(x w'') >= 0$ for each of its prefixes $w''$, so
  $w' in S$ and $w$ comes from $S -> 1 B 0 S$.

Induction on length finishes the argument.

#disclosures(llm: llm-note)

#pagebreak()

= Part (b)

Even-length strings whose second half contains an even number of 1s, that is,

$
{x y in Sigma^* | |x| = |y| "and" \#(1, y) "is even"}.
$

#boxed[
$
X &-> 0 | 1 & #h(1.5em) "the two one-symbol strings" \
E &-> epsilon | X E 0 | X O 1 & #h(1.5em) "even-length, second half has an even number of 1s" \
O &-> X O 0 | X E 1 & #h(1.5em) "even-length, second half has an odd number of 1s"
$
]

The start symbol is $E$. The three non-terminals generate the following
languages.

- $X$ generates the two strings $0$ and $1$.

- $E$ generates every string $x y$ with $|x| = |y|$ and $\#(1, y)$ even.

- $O$ generates every string $x y$ with $|x| = |y|$ and $\#(1, y)$ odd.

*Why this is correct.* Every rule other than $E -> epsilon$ adds one symbol at
the far left and one symbol at the far right, so a derivation of a string of
length $2 n$ applies exactly $n$ of them. The $n$ symbols added on the left, in
the order they were added, spell out the first half $x$, and the $n$ symbols
added on the right spell out the second half $y$ from its last symbol backwards.
The halves therefore always have equal length, and the only thing the rules need
to track is the parity of $\#(1, y)$.

- A symbol 0 placed on the right keeps that parity, which is why $E -> X E 0$ and
  $O -> X O 0$ leave the non-terminal unchanged.

- A symbol 1 placed on the right flips it, which is why $E -> X O 1$ and
  $O -> X E 1$ switch between the two non-terminals.

- The base case $E -> epsilon$ is correct because the empty second half contains
  zero 1s, and $O$ has no $epsilon$-rule for the same reason.

Formally, both inclusions follow by induction on $n$. Each rule preserves the
claimed description, as the previous paragraph shows. For the other direction,
let $x y$ have $|x| = |y| = n$.

- If $n = 0$, then $\#(1, y) = 0$ is even and $E -> epsilon$ applies.

- If $n >= 1$, write $x = a x'$ and $y = y' b$ with $a, b in Sigma$. Then
  $|x'| = |y'| = n - 1$, and $\#(1, y) = \#(1, y') + 1$ when $b = 1$, while
  $\#(1, y) = \#(1, y')$ when $b = 0$. So if $\#(1, y)$ is even, then $x' y'$ is
  generated by $E$ when $b = 0$ and by $O$ when $b = 1$, and the rules
  $E -> X E 0$ and $E -> X O 1$ produce $x y$. The odd case is symmetric.

#disclosures(llm: llm-note)

#pagebreak()

= Part (c)

$
{0^a 1^b 0^c 1^d | a, b, c, d >= 1 "and if" a = d "then" b = c}
$

#boxed[
$
S &-> O M I | G | H & #h(1.5em) "the language" \
G &-> 0 G 1 | 0 O I O 1 & #h(1.5em) 0^a 1^b 0^c 1^d "with" a > d \
H &-> 0 H 1 | 0 I O I 1 & #h(1.5em) 0^a 1^b 0^c 1^d "with" a < d \
M &-> 1 0 | 1 M 0 & #h(1.5em) 1^n 0^n "with" n >= 1 \
O &-> 0 | 0 O & #h(1.5em) 0^n "with" n >= 1 \
I &-> 1 | 1 I & #h(1.5em) 1^n "with" n >= 1
$
]

The six non-terminals generate the following languages.

- $O$ generates every non-empty string of 0s, that is, every $0^n$ with $n >= 1$.

- $I$ generates every non-empty string of 1s, that is, every $1^n$ with $n >= 1$.

- $M$ generates every string $1^n 0^n$ with $n >= 1$.

- $G$ generates every string $0^a 1^b 0^c 1^d$ with $a, b, c, d >= 1$ and $a > d$.

- $H$ generates every string $0^a 1^b 0^c 1^d$ with $a, b, c, d >= 1$ and $a < d$.

- $S$ generates every string $0^a 1^b 0^c 1^d$ with $a, b, c, d >= 1$ such that
  $b = c$ whenever $a = d$, which is the language asked for.

*Why this is correct.* The condition "if $a = d$ then $b = c$" is the same as
"$a != d$ or $b = c$", so the language is the union of three sets: the strings
with $b = c$, the strings with $a > d$, and the strings with $a < d$. The three
alternatives for $S$ generate exactly those three sets.

- $O M I$ generates $0^a 1^n 0^n 1^d$ for all $a, n, d >= 1$, which is exactly
  the set of strings of the required shape with $b = c$.

- A derivation from $G$ applies $G -> 0 G 1$ some $k >= 0$ times and then
  $G -> 0 O I O 1$, producing

  $
  0^k (0 med 0^p 1^q 0^r 1) 1^k = 0^(k + 1 + p) 1^q 0^r 1^(k + 1)
  $

  for some $p, q, r >= 1$. So $a = k + 1 + p$, $b = q$, $c = r$, $d = k + 1$, and
  $a - d = p >= 1$. Conversely, any string $0^a 1^b 0^c 1^d$ with $b, c >= 1$ and
  $a > d >= 1$ arises this way, by taking $k = d - 1$, $p = a - d$, $q = b$, and
  $r = c$.

- A derivation from $H$ likewise produces

  $
  0^k (0 med 1^p 0^q 1^r 1) 1^k = 0^(k + 1) 1^p 0^q 1^(r + 1 + k)
  $

  for some $p, q, r >= 1$. So $a = k + 1$, $b = p$, $c = q$, $d = k + 1 + r$, and
  $d - a = r >= 1$. Conversely, any string with $b, c >= 1$ and $d > a >= 1$
  arises by taking $k = a - 1$, $p = b$, $q = c$, and $r = d - a$.

Every string generated by $S$ therefore has the shape $0^a 1^b 0^c 1^d$ with all
four exponents at least 1, and satisfies $a != d$ or $b = c$, so it is in the
language. Conversely, a string of the language with $a = d$ must have $b = c$ and
is generated by $O M I$, and a string with $a != d$ is generated by $G$ or by
$H$. The grammar is ambiguous, since strings with $b = c$ and $a != d$ have
derivations of both kinds, but that is permitted here.

#pagebreak()

#disclosures(llm: llm-note)
